//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendingInfo
    {
        public System.Guid Id { get; set; }
        public string ActionName { get; set; }
        public string production { get; set; }
        public Nullable<int> StandardSalary { get; set; }
        public string Functions { get; set; }
        public string Date { get; set; }
        public Nullable<int> Department { get; set; }
        public string WorkInfo { get; set; }
        public string WorkMark { get; set; }
        public string WorkPhoto { get; set; }
        public Nullable<int> BearFees { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> HumanId { get; set; }
        public bool IsDraft { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public string Creatorname { get; set; }
        public Nullable<int> WorkContentId { get; set; }
    
        public virtual HumanBasicFile HumanBasicFile { get; set; }
        public virtual SShop SShop { get; set; }
    }
}
