//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DianJian
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Score { get; set; }
        public string DJContent { get; set; }
        public string DJTime { get; set; }
        public string VideoLink { get; set; }
        public Nullable<int> Face { get; set; }
        public Nullable<int> KOP { get; set; }
        public Nullable<int> WorkAttitude { get; set; }
        public Nullable<System.Guid> HumanId { get; set; }
        public string CreatedManager { get; set; }
        public string EditManagerID { get; set; }
        public bool IsDraft { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DraftCreateTime { get; set; }
    
        public virtual HumanBasicFile HumanBasicFile { get; set; }
    }
}
