//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanBasicFile
    {
        public HumanBasicFile()
        {
            this.AttendingInfo = new HashSet<AttendingInfo>();
            this.DianJian = new HashSet<DianJian>();
            this.Train = new HashSet<Train>();
        }
    
        public System.Guid Id { get; set; }
        public string uniNum { get; set; }
        public Nullable<int> city { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string NativePlace { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string IDcardNo { get; set; }
        public string IDcardPhoto { get; set; }
        public string BankCardPhoto { get; set; }
        public string Telephone { get; set; }
        public string BankNum { get; set; }
        public Nullable<int> BankId { get; set; }
        public string School { get; set; }
        public string Major { get; set; }
        public string GraduateTime { get; set; }
        public string Academic { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string speciality { get; set; }
        public string BWH { get; set; }
        public string InterfacePhoto { get; set; }
        public string Info { get; set; }
        public string CreatedManagerID { get; set; }
        public string EditManagerId { get; set; }
        public Nullable<System.Guid> Boss { get; set; }
        public string Remark { get; set; }
        public bool IsDraft { get; set; }
        public string HumanLevel { get; set; }
        public int TrainTimes { get; set; }
        public Nullable<int> LevelEditTimes { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<AttendingInfo> AttendingInfo { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual City City1 { get; set; }
        public virtual ICollection<DianJian> DianJian { get; set; }
        public virtual Managers Managers { get; set; }
        public virtual ICollection<Train> Train { get; set; }
    }
}
