//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SS_HRM_DBEntities : DbContext
    {
        public SS_HRM_DBEntities()
            : base("name=SS_HRM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttendingInfo> AttendingInfo { get; set; }
        public DbSet<Authority> Authority { get; set; }
        public DbSet<Bank> Bank { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<DianJian> DianJian { get; set; }
        public DbSet<Feedback> Feedback { get; set; }
        public DbSet<HumanBasicFile> HumanBasicFile { get; set; }
        public DbSet<LoginLog> LoginLog { get; set; }
        public DbSet<Managers> Managers { get; set; }
        public DbSet<MonthTraining> MonthTraining { get; set; }
        public DbSet<Notice> Notice { get; set; }
        public DbSet<Office> Office { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<ProductCategory> ProductCategory { get; set; }
        public DbSet<ReplyFeedback> ReplyFeedback { get; set; }
        public DbSet<Salesman> Salesman { get; set; }
        public DbSet<SShop> SShop { get; set; }
        public DbSet<TodayWork> TodayWork { get; set; }
        public DbSet<TomorrowWorkPlan> TomorrowWorkPlan { get; set; }
        public DbSet<Train> Train { get; set; }
        public DbSet<WorkContent> WorkContent { get; set; }
    }
}
