//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthTraining
    {
        public System.Guid Id { get; set; }
        public int TrainingCout { get; set; }
        public int Identification { get; set; }
        public string TrainContent { get; set; }
        public string TrainPicture { get; set; }
        public string TrainProduct { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.Guid ManagerId { get; set; }
        public Nullable<int> WorkContentid { get; set; }
    }
}
