//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyFeedback
    {
        public int Id { get; set; }
        public int TitleId { get; set; }
        public string ReplyContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateManId { get; set; }
    
        public virtual Feedback Feedback { get; set; }
    }
}
