//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman
    {
        public System.Guid Id { get; set; }
        public string ActivityName { get; set; }
        public string ActivityForm { get; set; }
        public string Adress { get; set; }
        public Nullable<int> LinCuCout { get; set; }
        public Nullable<int> LinCuMony { get; set; }
        public string LinCuPicture { get; set; }
        public Nullable<int> XingCuCout { get; set; }
        public Nullable<int> XingCuMony { get; set; }
        public string XingCuPicture { get; set; }
        public string Overfulfil { get; set; }
        public string Uncomplete { get; set; }
        public bool IsDraft { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.Guid> ManagerId { get; set; }
        public Nullable<int> WorkContentid { get; set; }
    }
}
