//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SShop
    {
        public SShop()
        {
            this.AttendingInfo = new HashSet<AttendingInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Code { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public virtual ICollection<AttendingInfo> AttendingInfo { get; set; }
        public virtual City City { get; set; }
    }
}
