//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodayWork
    {
        public int Id { get; set; }
        public System.Guid ManagerId { get; set; }
        public string Product { get; set; }
        public string WorkContent { get; set; }
        public string ToWhere { get; set; }
        public string LeftProblem { get; set; }
        public string needWhoseSupport { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> WorkContentid { get; set; }
    }
}
