//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public System.Guid Id { get; set; }
        public string TrainDate { get; set; }
        public string TrainStartTime { get; set; }
        public string TrainEndTime { get; set; }
        public string TrainProduction { get; set; }
        public Nullable<int> TrainScore { get; set; }
        public string Trainlecturer { get; set; }
        public Nullable<System.Guid> HumanrId { get; set; }
        public string Remark { get; set; }
        public bool IsDraft { get; set; }
        public string Creatorname { get; set; }
        public string Trainpro { get; set; }
        public Nullable<int> WorkContentId { get; set; }
    
        public virtual HumanBasicFile HumanBasicFile { get; set; }
    }
}
